-- AlterTable
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "childAges" INTEGER[] DEFAULT ARRAY[]::INTEGER[];

-- AlterTable
ALTER TABLE "booking_rooms" 
ADD COLUMN IF NOT EXISTS "adultsCount" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "basePricePerNight" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "childAges" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN IF NOT EXISTS "childrenCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "extraAdultChargePerNight" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "extraAdultsCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "extraChildChargePerNight" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "extraChildrenCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "freeChildrenCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "infantsCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "paidChildrenCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "roomTypeId" TEXT,
ADD COLUMN IF NOT EXISTS "totalPricePerNight" DECIMAL(10,2);
