export const ROOM_HIGHLIGHTS = [
    'Mountain View',
    'River View',
    'Pool View',
    'Garden View',
    'Ocean View',
    'Valley View',
    'Forest View',
    'Sunset View',
    'Private Balcony',
    'Jacuzzi',
    'Fireplace',
    'King Size Bed',
    'Queen Size Bed',
    'Twin Beds',
    'Spacious Room',
    'Interconnected Rooms',
    'Soundproofed',
    'Attached Washroom',
    'Bathtub',
] as const;

export const ROOM_INCLUSIONS = [
    'Breakfast Included',
    'Lunch Included',
    'Dinner Included',
    'All Meals Included (MAP)',
    'Welcome Drink',
    'Fruit Basket',
    'Free Wi-Fi',
    'Airport Transfer',
    'Railway Station Pickup',
    'Evening Snacks',
    'Tea/Coffee Maker',
    'Nature Walk',
    'Yoga Session',
    'Trekking',
    'Plantation Tour',
    'Campfire',
    'Bird Watching',
    'Indoor Games',
] as const;

export const ROOM_AMENITIES = [
    'Wi-Fi',
    'Air Conditioning (AC)',
    'Fan',
    'Room Heater',
    'TV',
    'Mini Fridge',
    'Electric Kettle',
    'Safe Box',
    'Telephone',
    'Hair Dryer',
    'Iron box',
    'Daily Housekeeping',
    'Toiletries',
    'Desk & Chair',
    'Wardrobe',
    'Sofa / Seating Area',
    'Extra Mattress',
    'Bathrobes',
    'Plush Towels',
    'Laundry Service',
] as const;
