name: Deploy to Staging Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /var/www/Resort-management-system/
            chmod +x deploy-staging.sh
            ./deploy-staging.sh
